baseURL: 'https://w3cdotorg.github.io/uv-tools/'
languageCode: en-us

# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage: fr

# Renders the default content language in subdir, e.g. /en/. The root directory / will redirect to /en/
defaultContentLanguageInSubdir: true

# Enable robots.txt generation
enableRobotsTXT: true

disableKinds:
- taxonomy
- taxonomyTerm

markup:
  goldmark:
    renderer:
      hardWraps: true

params:
  author: Nicolas Martignoni
  githubUsername: 'martignoni'
  accent: '#f98012'
  showBorder: 'true'
  backgroundColor: '#ffffff'
  matomoAnalytics:
    siteid: 4
    matomoroot: "stats.martignoni.net" # Do not add slashes
  menu:
    icon:
      - url: 'mailto:nicolas@martignoni.net'
        name: envelope-o
        weight: 1
      - url: 'https://github.com/martignoni/moodle-tool-guide'
        name: github
        weight: 2
  js: 'js/custom.js'

languages:
  en:
    languageName: English
    weight: 1
    title: Moodle Tool Guide
    slogan: Moodle Tool Guide for teachers and educators
    description: 'Moodle Tool Guide: A Quick Reference Guide for teachers and educators to use Moodle version 3 and later.'
    keywords:
    - Moodle
    - Moodle Tools
    - Moodle Tools Guide
    - Moodle Tool Guide
    - Moodle Tool Guide for teachers
    - Moodle Tools for teachers
    - Moodle Guide
    - Moodle Guide for teachers
    - Moodle Guide for instructors
    - Moodle Guide for trainers
    contentDir: content/en
    date_format: January 2, 2006
    menu:
      main:
        - url: /
          name: Home
          weight: 1
        - url: /about/
          name: About
          weight: 2
      icon:
        - url: 'https://github.com/martignoni/moodle-tool-guide'
          name: github
          weight: 2

  fr:
    languageName: Français
    weight: 2
    title: Guide des outils Moodle
    slogan: Guide des outils Moodle pour enseignant·es et formateur·trices
    description: "Guide des outils Moodle : un aide-mémoire pour l'utilisation de Moodle version 3 et ultérieures, destiné aux enseignantes et enseignants et aux formatrices et formateurs."
    keywords:
    - Moodle
    - Outils Moodle
    - Guide des outils Moodle
    - Outils Moodle pour enseignants
    - Guide des outils Moodle pour enseignants
    - Outils Moodle pour formateurs
    - Guide Moodle
    - Guide Moodle pour enseignants
    - Guide Moodle pour formateurs
    contentDir: content/fr
    date_format: 2 January 2006
    menu:
      main:
        - url: /
          name: Accueil
          weight: 1
        - url: /about/
          name: À propos
          weight: 2
      icon:
        - url: 'https://github.com/martignoni/moodle-tool-guide'
          name: github
          weight: 2

  nl:
    languageName: Nederlands
    weight: 6
    title: Moodle Gereedschapsgids
    slogan: Moodle Gereedschapsgids voor onderwijzers en trainers
    description: 'Moodle Gereedschapsgid voor leerkrachten: Een korte handleiding voor leerkrachten en trainers over het gebruik van Moodle versie 3 en nieuwer.'
    keywords:
    - Moodle
    - Moodle Gereedschappen
    - Moodle Gereedschapsgids
    - Moodle Gereedschap Gids
    - Moodle Gereerdschap Gids voor onderwijzers
    - Moodle Gereedschap voor docenten
    - Moodle Gids
    - Moodle Gids voor leraren
    - Moodle Gids voor docenten
    - Moodle Gids voor trainers
    - Moodle Gereedschapsgids voor onderwijzers
    - Moodle Gereedschapsgids voor leraren
    - Moodle Gereedschapsgids voor Onderwijzers en Leraren
    contentDir: content/nl
    date_format: 2 January 2006
    menu:
      main:
        - url: /
          name: Home
          weight: 1
        - url: /about/
          name: Over
          weight: 2
      icon:
        - url: 'https://github.com/martignoni/moodle-tool-guide'
          name: github
          weight: 2
