baseURL: 'https://capulb.github.io/uv-tools/'
languageCode: en-us

# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage: fr

# Renders the default content language in subdir, e.g. /en/. The root directory / will redirect to /en/
defaultContentLanguageInSubdir: true

# Enable robots.txt generation
enableRobotsTXT: true
enableEmoji: true

disableKinds:
- taxonomy

markup:
  goldmark:
    renderer:
      hardWraps: true

params:
  author: Équipe CAP
  githubUsername: 'capulb'
  accent: '#f98012'
  showBorder: 'true'
  backgroundColor: '#ffffff'
  menu:
    icon:
      - url: 'mailto:cap@ulb.be'
        name: envelope-o
        weight: 1
      - url: 'https://github.com/capulb/uv-tools'
        name: github
        weight: 2
  js: 'js/custom.js'

languages:
  en:
    languageName: English
    weight: 1
    params: 
      title: UV - ULB Tool Guide
      slogan: UV - ULB Tool Guide for teachers and educators
      description: 'UV Tool Guide: A Quick Reference Guide for teachers and educators to use the Université Virtuelle at ULB.'
      keywords:
      - Moodle
      - Moodle Tools
      - Moodle Tools Guide
      - Moodle Tool Guide
      - Moodle Tool Guide for teachers
      - Moodle Tools for teachers
      - Moodle Guide
      - Moodle Guide for teachers
      - Moodle Guide for instructors
      - Moodle Guide for trainers
      - Université virtuelle
      - UV
      - Université libre de Bruxelles
      date_format: January 2, 2006
    contentDir: content/en
    menu:
      main:
        - url: 
          name: Home
          weight: 1
        - url: about/
          name: About
          weight: 2
      icon:
        - url: https://uv.ulb.ac.be
          title: UV
          name: external-link
          weight: 3
       

  fr:
    languageName: Français
    weight: 2
    params:
      title: Guide des outils UV
      slogan: Guide des outils sur l'Université Virtuelle pour enseignant·es et formateur·rices
      description: "Guide des outils UV : un aide-mémoire pour l'utilisation de l'Université Virtuelle - Moodle version 3 et ultérieures -, destiné aux enseignantes et enseignants et aux formatrices et formateurs."
      keywords:
      - Moodle
      - Outils Moodle
      - Guide des outils Moodle
      - Outils Moodle pour enseignants
      - Guide des outils Moodle pour enseignants
      - Outils Moodle pour formateurs
      - Guide Moodle
      - Guide Moodle pour enseignants
      - Guide Moodle pour formateurs
      - Université Virtuelle
      - UV
      - Université libre de Bruxelles
      date_format: 2 January 2006
    contentDir: content/fr
    menu:
      main:
        - url: 
          name: Accueil
          weight: 1
        - url: about/
          name: À propos
          weight: 2
      icon:
        - url: https://uv.ulb.ac.be
          title: UV
          name: external-link
          weight: 3
